### PR TITLE
Feature/firefox version

### LINKED ISSUE #1: make into a web extension
thanks to the prompting of @birtles, we can make this extension more accessible for non chrome users: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension

free for anyone to pick up e.g. @dance2die if you wish

### PR DESCRIPTION
**Pull request by nero2009**
This Pull request ported the chrome extension to firefox.
closes #1

### CODE REVIEW

**Comment by swyxio** [comment]
cool! do you wanna publish it? it doesnt have to be me doing it. also lets take out those 2 console.logs you left in there :)

**Comment by nero2009** [comment]
Ok I will make those changes then publish it.

**Comment by nero2009** [comment]
Just Published https://addons.mozilla.org/en-US/firefox/addon/netlify-browser-extension/

**Comment by swyxio** [comment]
awesome

**Pull request merged**
